version: '3.8'

services:
  server:
    image: ubuntu-with-node
    build:
      context: .
      dockerfile: ./config/Dockerfile
    ports:
      - 3000:3000
    command: node app.js
    depends_on:
      - database
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: foobar
    ports:
      - '3306:3306'
  